# Generated by Django 5.2.17 on 2026-08-07 23:24

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordem de exibição (menor primeiro)', verbose_name='Ordem')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('unit', models.CharField(choices=[('unit', 'Unidade'), ('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro'), ('pack', 'Pacote'), ('box', 'Caixa')], default='unit', max_length=20, verbose_name='Unidade de Medida')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade atual em estoque', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em Estoque')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade mínima para alerta de estoque', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Preço de compra do produto', max_digits=10, validators=[apps.core.validators.validate_positive], verbose_name='Preço de Custo')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Preço de venda do produto', max_digits=10, validators=[apps.core.validators.validate_positive], verbose_name='Preço de Venda')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('image', models.ImageField(blank=True, help_text='Imagem do produto', null=True, upload_to='products/%Y/%m/', verbose_name='Imagem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída'), ('adjustment', 'Ajuste'), ('loss', 'Perda')], db_index=True, max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('previous_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Anterior')),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Nova Quantidade')),
                ('reason', models.CharField(help_text='Motivo da movimentação', max_length=200, verbose_name='Motivo')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'movement_type'], name='products_in_product_3999d3_idx'), models.Index(fields=['created_at'], name='products_in_created_58a9aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'is_active'], name='products_pr_name_59cb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
    ]
