# Generated by Django 5.2.17 on 2026-08-06 12:02

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('registration_number', models.CharField(blank=True, help_text='Número de registro profissional (se aplicável)', max_length=20, null=True, unique=True, verbose_name='Número de Registro')),
                ('specialty', models.CharField(blank=True, help_text='Especialidade principal do barbeiro', max_length=100, verbose_name='Especialidade')),
                ('bio', models.TextField(blank=True, help_text='Breve descrição sobre o barbeiro', max_length=500, verbose_name='Biografia')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Anos de experiência profissional', verbose_name='Anos de Experiência')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Percentual de comissão sobre os serviços', max_digits=5, validators=[apps.core.validators.validate_percentage], verbose_name='Percentual de Comissão')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('on_vacation', 'Em Férias'), ('on_leave', 'Afastado')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Média de avaliações (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('total_services', models.PositiveIntegerField(default=0, help_text='Total de serviços realizados', verbose_name='Total de Serviços')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='barber_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Barbeiro',
                'verbose_name_plural': 'Barbeiros',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('type', models.CharField(choices=[('vacation', 'Férias'), ('sick_leave', 'Licença Médica'), ('personal', 'Assunto Pessoal'), ('holiday', 'Feriado'), ('other', 'Outro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(db_index=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(db_index=True, verbose_name='Data de Término')),
                ('description', models.TextField(blank=True, help_text='Motivo ou descrição do afastamento', max_length=200, verbose_name='Descrição')),
                ('is_approved', models.BooleanField(default=False, help_text='Se o afastamento foi aprovado', verbose_name='Aprovado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_offs', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='barbers.barber', verbose_name='Barbeiro')),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordem de exibição (menor primeiro)', verbose_name='Ordem')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], db_index=True, verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(help_text='Horário que o barbeiro começa a trabalhar', verbose_name='Horário de Início')),
                ('end_time', models.TimeField(help_text='Horário que o barbeiro termina de trabalhar', verbose_name='Horário de Término')),
                ('break_start', models.TimeField(blank=True, help_text='Horário de início do intervalo', null=True, verbose_name='Início do Intervalo')),
                ('break_end', models.TimeField(blank=True, help_text='Horário de fim do intervalo', null=True, verbose_name='Fim do Intervalo')),
                ('is_available', models.BooleanField(default=True, help_text='Se o barbeiro está disponível neste dia', verbose_name='Disponível')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='barbers.barber', verbose_name='Barbeiro')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'ordering': ['barber', 'day_of_week', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='barber',
            index=models.Index(fields=['status', 'rating'], name='barbers_bar_status_afa2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='barber',
            index=models.Index(fields=['user', 'is_active'], name='barbers_bar_user_id_ffab12_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['barber', 'start_date', 'end_date'], name='barbers_tim_barber__99c40f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['type', 'is_approved'], name='barbers_tim_type_d5fbd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('barber', 'day_of_week')},
        ),
    ]
