# Generated by Django 5.2.17 on 2026-08-07 23:24

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('full_name', models.CharField(db_index=True, max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, help_text='CPF do cliente (apenas números)', max_length=14, null=True, unique=True, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('phone', models.CharField(db_index=True, help_text='Telefone com DDD (apenas números)', max_length=15, validators=[apps.core.validators.validate_phone], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('address', models.TextField(blank=True, max_length=200, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('blocked', 'Bloqueado')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Pontos acumulados no programa de fidelidade', verbose_name='Pontos de Fidelidade')),
                ('total_visits', models.PositiveIntegerField(default=0, help_text='Número total de visitas à barbearia', verbose_name='Total de Visitas')),
                ('last_visit', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Última Visita')),
                ('notes', models.TextField(blank=True, help_text='Observações gerais sobre o cliente', max_length=500, verbose_name='Observações')),
                ('preferred_barber', models.ForeignKey(blank=True, help_text='Barbeiro que o cliente prefere', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='barbers.barber', verbose_name='Barbeiro Preferido')),
                ('preferred_services', models.ManyToManyField(blank=True, help_text='Serviços que o cliente mais utiliza', related_name='preferred_by_customers', to='services.service', verbose_name='Serviços Preferidos')),
                ('user', models.OneToOneField(blank=True, help_text='Usuário associado ao cliente (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('type', models.CharField(choices=[('appointment', 'Agendamento'), ('visit', 'Visita'), ('points_earned', 'Pontos Ganhos'), ('points_used', 'Pontos Utilizados'), ('feedback', 'Feedback'), ('other', 'Outro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(help_text='Descrição da atividade', max_length=200, verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON', verbose_name='Metadados')),
                ('phone', models.CharField(db_index=True, help_text='Telefone com DDD (apenas números)', max_length=15, unique=True, validators=[apps.core.validators.validate_phone], verbose_name='Telefone')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Histórico do Cliente',
                'verbose_name_plural': 'Históricos dos Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['full_name', 'phone'], name='customers_c_full_na_75bc12_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', 'last_visit'], name='customers_c_status_ea8e41_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['loyalty_points'], name='customers_c_loyalty_aee44b_idx'),
        ),
    ]
