# Generated by Django 5.2.17 on 2026-08-05 19:03

import apps.core.validators
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(blank=True, help_text='CPF do usuário (apenas números)', max_length=14, null=True, unique=True, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('phone', models.CharField(blank=True, help_text='Telefone com DDD (apenas números)', max_length=15, validators=[apps.core.validators.validate_phone], verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('user_type', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('barber', 'Barbeiro'), ('receptionist', 'Recepcionista'), ('customer', 'Cliente')], db_index=True, default='customer', max_length=20, verbose_name='Tipo de Usuário')),
                ('avatar', models.ImageField(blank=True, help_text='Imagem de perfil do usuário', null=True, upload_to='profiles/avatars/%Y/%m/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, help_text='Breve descrição sobre o usuário', max_length=500, verbose_name='Biografia')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para bloquear o acesso do usuário', verbose_name='Ativo')),
                ('last_activity', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'auth_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receber notificações por email', verbose_name='Notificações por Email')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receber notificações por SMS', verbose_name='Notificações por SMS')),
                ('whatsapp_notifications', models.BooleanField(default=True, help_text='Receber notificações por WhatsApp', verbose_name='Notificações por WhatsApp')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English')], default='pt-br', max_length=10, verbose_name='Idioma')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=20, verbose_name='Tema')),
                ('address', models.TextField(blank=True, max_length=200, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='auth_user_usernam_15cc09_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='auth_user_email_db7920_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cpf'], name='auth_user_cpf_3b96f7_idx'),
        ),
    ]
