# Generated by Django 5.2.17 on 2026-08-07 23:24

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordem de exibição (menor primeiro)', verbose_name='Ordem')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Classe do ícone (ex: fas fa-cut)', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#0d6efd', help_text='Cor em hexadecimal (ex: #0d6efd)', max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável gerada automaticamente', max_length=200, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordem de exibição (menor primeiro)', verbose_name='Ordem')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do serviço', max_length=500, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do serviço', max_digits=10, validators=[apps.core.validators.validate_positive], verbose_name='Preço')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Tempo estimado para realização do serviço', validators=[django.core.validators.MinValueValidator(5)], verbose_name='Duração (minutos)')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Percentual de comissão para o barbeiro', max_digits=5, validators=[apps.core.validators.validate_percentage], verbose_name='Percentual de Comissão')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('discontinued', 'Descontinuado')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, help_text='Imagem ilustrativa do serviço', null=True, upload_to='services/%Y/%m/', verbose_name='Imagem')),
                ('total_performed', models.PositiveIntegerField(default=0, help_text='Número total de vezes que este serviço foi realizado', verbose_name='Total Realizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantidade do produto necessária por serviço', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_services', to='products.product', verbose_name='Produto')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_products', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Produto do Serviço',
                'verbose_name_plural': 'Produtos dos Serviços',
                'ordering': ['service', 'product'],
                'unique_together': {('service', 'product')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='required_products',
            field=models.ManyToManyField(blank=True, related_name='services_using_product', through='services.ServiceProduct', to='products.product', verbose_name='Produtos Necessários'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name', 'status'], name='services_se_name_0d8ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'status'], name='services_se_categor_03dc52_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='services_se_price_4a7bf9_idx'),
        ),
    ]
