# Generated by Django 5.2.17 on 2026-08-06 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantidade do produto necessária por serviço', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_services', to='products.product', verbose_name='Produto')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_products', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Produto do Serviço',
                'verbose_name_plural': 'Produtos dos Serviços',
                'ordering': ['service', 'product'],
                'unique_together': {('service', 'product')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='required_products',
            field=models.ManyToManyField(blank=True, related_name='services_using_product', through='services.ServiceProduct', to='products.product', verbose_name='Produtos Necessários'),
        ),
    ]
