# Generated by Django 5.2.17 on 2026-08-06 12:38

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barbers', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Aberto em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo inicial em dinheiro', max_digits=10, verbose_name='Saldo Inicial')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo final em dinheiro', max_digits=10, null=True, verbose_name='Saldo Final')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de Receitas')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de Despesas')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de Comissões')),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo esperado = Saldo Inicial + Receitas - Despesas', max_digits=10, null=True, verbose_name='Saldo Esperado')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o caixa', max_length=500, verbose_name='Observações')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_registers', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_registers', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.core.validators.validate_positive], verbose_name='Valor')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentual aplicado', max_digits=5, verbose_name='Percentual')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('period_start', models.DateField(help_text='Início do período de competência', verbose_name='Período Início')),
                ('period_end', models.DateField(help_text='Fim do período de competência', verbose_name='Período Fim')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='appointments.appointment', verbose_name='Agendamento')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='barbers.barber', verbose_name='Barbeiro')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Pago por')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('transaction_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('commission', 'Comissão')], db_index=True, max_length=20, verbose_name='Tipo de Transação')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('card_debit', 'Cartão Débito'), ('card_credit', 'Cartão Crédito'), ('pix', 'PIX'), ('transfer', 'Transferência'), ('other', 'Outro')], db_index=True, max_length=20, verbose_name='Forma de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da transação', max_digits=10, validators=[apps.core.validators.validate_positive], verbose_name='Valor')),
                ('description', models.CharField(help_text='Descrição da transação', max_length=200, verbose_name='Descrição')),
                ('transaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da Transação')),
                ('reference', models.CharField(blank=True, help_text='Número de referência ou código', max_length=100, verbose_name='Referência')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor da comissão para o barbeiro', max_digits=10, verbose_name='Valor da Comissão')),
                ('commission_paid', models.BooleanField(default=False, help_text='Se a comissão já foi paga', verbose_name='Comissão Paga')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='appointments.appointment', verbose_name='Agendamento')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='barbers.barber', verbose_name='Barbeiro')),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.cashregister', verbose_name='Caixa')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['status', 'opened_at'], name='finance_cas_status_fad0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['barber', 'status'], name='finance_com_barber__8ca7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'paid_at'], name='finance_com_status_51977f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='finance_tra_transac_4c1a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'transaction_date'], name='finance_tra_custome_28c13e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['barber', 'commission_paid'], name='finance_tra_barber__adf9ce_idx'),
        ),
    ]
