# Generated by Django 5.2.17 on 2026-08-07 00:33

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome do Gasto')),
                ('category', models.CharField(choices=[('rent', 'Aluguel'), ('salary', 'Salário'), ('water', 'Água'), ('electricity', 'Energia'), ('internet', 'Internet'), ('supplies', 'Suprimentos'), ('marketing', 'Marketing'), ('maintenance', 'Manutenção'), ('insurance', 'Seguro'), ('other', 'Outros')], db_index=True, max_length=20, verbose_name='Categoria')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor do gasto', max_digits=10, validators=[apps.core.validators.validate_positive], verbose_name='Valor')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semester', 'Semestral'), ('annual', 'Anual'), ('once', 'Única')], db_index=True, default='monthly', max_length=20, verbose_name='Frequência')),
                ('due_day', models.PositiveSmallIntegerField(default=1, help_text='Dia do mês para vencimento (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('description', models.TextField(blank=True, help_text='Detalhes adicionais do gasto', max_length=300, verbose_name='Descrição')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('last_charged', models.DateField(blank=True, help_text='Data da última cobrança realizada', null=True, verbose_name='Última Cobrança')),
                ('next_charge', models.DateField(blank=True, help_text='Data da próxima cobrança', null=True, verbose_name='Próxima Cobrança')),
            ],
            options={
                'verbose_name': 'Gasto Fixo',
                'verbose_name_plural': 'Gastos Fixos',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='finance_fix_categor_8efe6e_idx'), models.Index(fields=['next_charge'], name='finance_fix_next_ch_6d8d70_idx')],
            },
        ),
    ]
