# Generated by Django 5.2.17 on 2026-08-06 12:44

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0002_serviceproduct_service_required_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome do Plano')),
                ('description', models.TextField(blank=True, help_text='Descrição dos benefícios do plano', max_length=500, verbose_name='Descrição')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semester', 'Semestral'), ('annual', 'Anual')], db_index=True, max_length=20, verbose_name='Ciclo de Cobrança')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do plano por ciclo', max_digits=10, validators=[apps.core.validators.validate_positive], verbose_name='Preço')),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa única de ativação do plano', max_digits=10, verbose_name='Taxa de Ativação')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de desconto em serviços', max_digits=5, validators=[apps.core.validators.validate_percentage], verbose_name='Desconto em Serviços')),
                ('free_services_per_month', models.PositiveIntegerField(default=0, help_text='Número de serviços gratuitos por mês', verbose_name='Serviços Gratuitos por Mês')),
                ('priority_booking', models.BooleanField(default=False, help_text='Cliente tem prioridade no agendamento', verbose_name='Agendamento Prioritário')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('discontinued', 'Descontinuado')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('total_subscribers', models.PositiveIntegerField(default=0, help_text='Número total de assinantes ativos', verbose_name='Total de Assinantes')),
                ('exclusive_services', models.ManyToManyField(blank=True, help_text='Serviços disponíveis apenas para este plano', related_name='exclusive_plans', to='services.service', verbose_name='Serviços Exclusivos')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('start_date', models.DateField(db_index=True, help_text='Data de início da assinatura', verbose_name='Data de Início')),
                ('end_date', models.DateField(db_index=True, help_text='Data de término da assinatura', verbose_name='Data de Término')),
                ('next_billing_date', models.DateField(db_index=True, help_text='Data da próxima cobrança', verbose_name='Próxima Cobrança')),
                ('cancelled_at', models.DateField(blank=True, help_text='Data de cancelamento da assinatura', null=True, verbose_name='Cancelado em')),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Preço pago no momento da assinatura', max_digits=10, verbose_name='Preço Pago')),
                ('setup_fee_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa de ativação paga', max_digits=10, verbose_name='Taxa de Ativação Paga')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('pending', 'Pendente')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('free_services_used', models.PositiveIntegerField(default=0, help_text='Quantos serviços gratuitos já foram utilizados', verbose_name='Serviços Gratuitos Utilizados')),
                ('last_free_service_used', models.DateField(blank=True, help_text='Data do último serviço gratuito utilizado', null=True, verbose_name='Último Serviço Gratuito')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão Débito'), ('pix', 'PIX'), ('bank_slip', 'Boleto'), ('cash', 'Dinheiro')], default='credit_card', max_length=20, verbose_name='Forma de Pagamento')),
                ('auto_renew', models.BooleanField(default=True, help_text='Renovar a assinatura automaticamente', verbose_name='Renovação Automática')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customer', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('action', models.CharField(choices=[('created', 'Criada'), ('activated', 'Ativada'), ('suspended', 'Suspensa'), ('cancelled', 'Cancelada'), ('renewed', 'Renovada'), ('expired', 'Expirada'), ('payment', 'Pagamento')], db_index=True, max_length=20, verbose_name='Ação')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da ação', max_length=500, verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON', verbose_name='Metadados')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_actions', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.subscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Histórico da Assinatura',
                'verbose_name_plural': 'Históricos das Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['name', 'status'], name='subscriptio_name_18f5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['billing_cycle', 'status'], name='subscriptio_billing_e7f324_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='subscriptio_custome_cea13a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_f7cbce_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date', 'status'], name='subscriptio_end_dat_1aba83_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_billing_date'], name='subscriptio_next_bi_0e9626_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('customer', 'plan', 'status')},
        ),
    ]
