# Generated by Django 5.2.17 on 2026-08-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição do relatório', max_length=500, verbose_name='Descrição')),
                ('report_type', models.CharField(choices=[('financial', 'Financeiro'), ('sales', 'Vendas'), ('appointments', 'Agendamentos'), ('customers', 'Clientes'), ('barbers', 'Barbeiros'), ('services', 'Serviços'), ('products', 'Produtos'), ('subscriptions', 'Assinaturas'), ('custom', 'Personalizado')], db_index=True, max_length=20, verbose_name='Tipo de Relatório')),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON')], default='html', max_length=10, verbose_name='Formato')),
                ('query', models.TextField(blank=True, help_text='Query SQL personalizada (para relatórios customizados)', verbose_name='Query')),
                ('fields', models.JSONField(default=list, help_text='Lista de campos a serem exibidos no relatório', verbose_name='Campos')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtros disponíveis para o relatório', verbose_name='Filtros')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('is_system', models.BooleanField(default=False, help_text='Relatório padrão do sistema', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('parameters', models.JSONField(default=dict, help_text='Parâmetros usados na execução', verbose_name='Parâmetros')),
                ('result_file', models.FileField(blank=True, help_text='Arquivo gerado pelo relatório', null=True, upload_to='reports/%Y/%m/', verbose_name='Arquivo Resultado')),
                ('result_data', models.JSONField(blank=True, help_text='Dados do relatório em formato JSON', null=True, verbose_name='Dados Resultado')),
                ('rows_count', models.PositiveIntegerField(default=0, help_text='Número de linhas no relatório', verbose_name='Linhas Geradas')),
                ('execution_time', models.DurationField(blank=True, help_text='Tempo gasto para gerar o relatório', null=True, verbose_name='Tempo de Execução')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro se a execução falhou', verbose_name='Mensagem de Erro')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_executed', to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatórios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', 'status'], name='reports_rep_templat_36d6a9_idx'), models.Index(fields=['status', 'created_at'], name='reports_rep_status_8339bb_idx')],
            },
        ),
    ]
