# Generated by Django 5.2.17 on 2026-08-06 12:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('start_time', models.DateTimeField(db_index=True, help_text='Data e hora de início do agendamento', verbose_name='Data e Hora de Início')),
                ('end_time', models.DateTimeField(db_index=True, help_text='Data e hora de término do agendamento', verbose_name='Data e Hora de Término')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('no_show', 'Não Compareceu')], db_index=True, default='scheduled', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('partial', 'Parcial'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Status do Pagamento')),
                ('service_price', models.DecimalField(decimal_places=2, help_text='Preço do serviço no momento do agendamento', max_digits=10, verbose_name='Preço do Serviço')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto aplicado ao agendamento', max_digits=10, verbose_name='Desconto')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Preço final após descontos', max_digits=10, verbose_name='Preço Final')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor da comissão para o barbeiro', max_digits=10, verbose_name='Valor da Comissão')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Avaliação do cliente (0-5)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('feedback', models.TextField(blank=True, help_text='Feedback do cliente sobre o serviço', max_length=500, verbose_name='Feedback')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o agendamento', max_length=500, verbose_name='Observações')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Motivo do cancelamento do agendamento', max_length=200, verbose_name='Motivo do Cancelamento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='barbers.barber', verbose_name='Barbeiro')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customer', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['barber', 'start_time', 'status'], name='appointment_barber__5068dd_idx'), models.Index(fields=['customer', 'start_time'], name='appointment_custome_024480_idx'), models.Index(fields=['status', 'start_time'], name='appointment_status_74937b_idx')],
                'unique_together': {('barber', 'start_time'), ('customer', 'start_time')},
            },
        ),
    ]
