# Generated by Django 5.2.17 on 2026-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Chave da sessão para agendamentos de visitantes', max_length=40, null=True, verbose_name='Chave de Sessão'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço final após descontos', max_digits=10, verbose_name='Preço Final'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do serviço no momento do agendamento', max_digits=10, verbose_name='Preço do Serviço'),
        ),
    ]
