# Generated by Django 5.2.17 on 2026-08-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_barber_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='barber_profit',
        ),
    ]
