# Generated by Django 5.2.17 on 2026-08-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_barber_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lucro gerado para o barbeiro', max_digits=10, verbose_name='Lucro do Barbeiro'),
        ),
    ]
