# Generated by Django 5.2.17 on 2026-08-06 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('email_appointment_confirmation', models.BooleanField(default=True, verbose_name='Email - Confirmação de Agendamento')),
                ('email_appointment_reminder', models.BooleanField(default=True, verbose_name='Email - Lembrete de Agendamento')),
                ('email_appointment_cancelled', models.BooleanField(default=True, verbose_name='Email - Agendamento Cancelado')),
                ('email_payment_received', models.BooleanField(default=True, verbose_name='Email - Pagamento Recebido')),
                ('email_low_stock', models.BooleanField(default=True, verbose_name='Email - Estoque Baixo')),
                ('email_promotional', models.BooleanField(default=False, verbose_name='Email - Promocionais')),
                ('system_appointment_confirmation', models.BooleanField(default=True, verbose_name='Sistema - Confirmação de Agendamento')),
                ('system_appointment_reminder', models.BooleanField(default=True, verbose_name='Sistema - Lembrete de Agendamento')),
                ('system_appointment_cancelled', models.BooleanField(default=True, verbose_name='Sistema - Agendamento Cancelado')),
                ('system_appointment_completed', models.BooleanField(default=True, verbose_name='Sistema - Agendamento Concluído')),
                ('system_low_stock', models.BooleanField(default=True, verbose_name='Sistema - Estoque Baixo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificações',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Desative para fazer exclusão lógica do registro', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('type', models.CharField(choices=[('appointment_confirmation', 'Confirmação de Agendamento'), ('appointment_reminder', 'Lembrete de Agendamento'), ('appointment_cancelled', 'Agendamento Cancelado'), ('appointment_completed', 'Agendamento Concluído'), ('payment_received', 'Pagamento Recebido'), ('low_stock', 'Estoque Baixo'), ('customer_birthday', 'Aniversário do Cliente'), ('system_alert', 'Alerta do Sistema'), ('promotional', 'Promocional')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(max_length=1000, verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, help_text='Link para redirecionar ao clicar na notificação', max_length=200, verbose_name='Link')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais da notificação', verbose_name='Metadados')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
            },
        ),
    ]
